### ISSUE TITLE
Suggested topic restructure

### ISSUE THREAD

**Issue by bluetarpmedia** [VsixCommunity/docs#9]
Right now the topics under **Walkthroughs** are focused on things like commands, tool windows, options, notifications. I'd suggest renaming this category to something like **Extending the UI**, and then using **Walkthroughs** for functional scenarios like:

* How to customize the Editor margin?
* How to build the solution?
* How to add or remove a breakpoint?
* How to nest files in Solution Explorer?
* How to open a new text file in the Editor?
* How to enumerate all files in a project?
* How to intercept key strokes in the Editor?
* etc

**Comment by madskristensen** [comment]
The current structure is to use the word *Recipe* instead of *Walkthroughs*, and then I've added a new section called *Tips & tricks* for small how-to's.

**Comment by bluetarpmedia** [comment]
Fantastic, nice one Mads!
